- name: Start Nexus Stack
  hosts: localhost
  connection: local
  gather_facts: False
  become: False
  vars_files:
  - vars/nexus.yaml
  tasks:
  - include: tasks/private_nexus_stack.yaml
    when: private|bool
  - include: tasks/public_nexus_stack.yaml
    when: not private|bool